<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.10" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="MySql.Data" Version="9.7.0" />
    <PackageReference Include="NewLife.Redis" Version="6.5.2026.601" />
    <PackageReference Include="NewLife.XCode" Version="11.27.2026.601" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NuGet.Protocol" Version="6.12.5" />
    <PackageReference Include="Senparc.NeuChar" Version="2.6.2" />
    <PackageReference Include="Senparc.Weixin" Version="6.23.1" />
    <PackageReference Include="Senparc.Weixin.MP" Version="16.24.2" />
    <PackageReference Include="Senparc.Weixin.TenPay" Version="1.18.1" />
    <PackageReference Include="Senparc.Weixin.WxOpen" Version="3.26.1" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\COMCMS.API\COMCMS.API.csproj" />
    <ProjectReference Include="..\COMCMS.Common\COMCMS.Common.csproj" />
    <ProjectReference Include="..\COMCMS.Core\COMCMS.Core.csproj" />
    <ProjectReference Include="..\Lib.Core\Lib.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\AdminCP\Data\" />
    <Folder Include="Areas\AdminCP\Models\" />
    <Folder Include="wwwroot\lib\webuploader\" />
    <Folder Include="wwwroot\userfiles\" />
    <Folder Include="Configuration\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\my97\lang\en.js" />
    <None Include="wwwroot\js\my97\lang\zh-cn.js" />
    <None Include="wwwroot\js\my97\lang\zh-tw.js" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.Development.local.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
